name: OpenAPI Validator

on:
  push:
    branches:
      - main
    paths:
      - auth-server-open-api-spec.yaml
      - open-api-spec.yaml
  pull_request:
    branches:
      - main
    paths:
      - auth-server-open-api-spec.yaml
      - open-api-spec.yaml

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Validate open-api-spec.yaml
        run: |
          echo "{\"extends\":[\"spectral:oas\",\"spectral:asyncapi\"]}" >> .spectral.json
          npx @stoplight/spectral-cli lint open-api-spec.yaml

      - name: Validate auth-server-open-api-spec.yaml
        run: |
          npx @stoplight/spectral-cli lint auth-server-open-api-spec.yaml
